### ISSUE TITLE
pipenv.vendor.plette.models.base.ValidationError while installing

### ISSUE THREAD

**Issue by rlevitsky** [kedarv/votey#34]
Hi Dev Team!

While following your manual, I run "/usr/local/bin/pipenv install -d" and see the "pipenv.vendor.plette.models.base.ValidationError". Please find the full output below.

Could you please help me finding and solving the issue?

```
# /usr/local/bin/pipenv install -d
Creating a virtualenv for this project...
Pipfile: /home/rlevytskyi/votey/Pipfile
Using /bin/python3.8 (3.8.13) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.8.13.final.0-64 in 2149ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/votey-uhgWhCuh, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/votey-uhgWhCuh
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    do_install(
  File "/usr/local/lib/python3.8/site-packages/pipenv/routines/install.py", line 193, in do_install
    do_init(
  File "/usr/local/lib/python3.8/site-packages/pipenv/routines/install.py", line 781, in do_init
    new_hash = project.calculate_pipfile_hash()
  File "/usr/local/lib/python3.8/site-packages/pipenv/project.py", line 1086, in calculate_pipfile_hash
    p = plette.Pipfile.load(pf)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 65, in load
    return cls(data)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 49, in __init__
    self.validate(data)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 49, in validate
    PackageCollection.validate(data[category])
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 125, in validate
    cls.item_class.validate(d)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/models/packages.py", line 24, in validate
    super(Package, cls).validate({"__package__": data})
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 81, in validate
    return validate(cls, data)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 38, in validate
    raise ValidationError(data, v)
pipenv.vendor.plette.models.base.ValidationError: {'__package__': True}
__package__: none or more than one rule validate
__package__: {'oneof definition 0': ['must be of string type'], 'oneof definition 1': ['must be of dict type']}
```

**Comment by rlevitsky** [comment]
I was able to run it by installing all to my pip manually.

In case some interested, I had to replace OAuth with OAuth v2 to make it work.

**Comment by kedarv** [comment]
I ended up switching this package to poetry, so it should work now with `poetry install`
